spring.application.name=Appmobile

## Database Properties
spring.datasource.url = jdbc:mysql://localhost:3306/uninassau?useSSL=false
spring.datasource.username = root
spring.datasource.password = 

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true